### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by hiradary** [chabokpush/chabok-client-rn-js#6]
اپ به درستی لینک شده و پروژه بیلد میشود اما وقتی اپلیکیشن رو باز میکنم کرش میکند

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">اپ به درستی لینک شده و پروژه بیلد میشود اما وقتی اپلیکیشن رو باز میکنم کرش میکند</p>
</blockquote>
<p dir="rtl">لطفا اطلاع بیشتری در اختیار ما قرار دهید:</p>
<p dir="rtl"> نوع پلتفرم: </p>
<p dir="rtl">مدل دستگاه:</p>
<p dir="rtl">نسخه سیستم‌عامل:</p>
<p dir="rtl">خطای رخ داده شده در logcat یا xcode log را برای ما اینجا قرار دهید</p>

**Comment by hiradary** [comment]
> > اپ به درستی لینک شده و پروژه بیلد میشود اما وقتی اپلیکیشن رو باز میکنم کرش میکند
> 
> لطفا اطلاع بیشتری در اختیار ما قرار دهید:
> 
> نوع پلتفرم:
> 
> مدل دستگاه:
> 
> نسخه سیستم‌عامل:
> 
> خطای رخ داده شده در logcat یا xcode log را برای ما اینجا قرار دهید

Platform: Android
Device: Samsung Galaxy S7 (Android 8)
OS: macOS Mojave 10.14
React Native 0.51.0, node 10.12

از لاگ کت خطا ندارم

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">از لاگ کت خطا ندارم</p>
</blockquote>

<p dir="rtl">لطفا log cat رو در حالت no filter قرار بدید اونجا خطای کرش رخ داده شده رو برای ما ارسال کنید.</p>

**Comment by hiradary** [comment]
> > از لاگ کت خطا ندارم
> 
> لطفا log cat رو در حالت no filter قرار دهید اونجا خطای کرش رخ داده شده رو برای ما ارسال کنید.

```
       --------- beginning of crash
12-24 15:38:19.823 3417-3705/com.almaseshomal.baamanbusiness E/AndroidRuntime: FATAL EXCEPTION: Thread-45
                                                                               Process: com.almaseshomal.baamanbusiness, PID: 3417
                                                                               java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
                                                                                   at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
                                                                                   at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
                                                                                   at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:783)
                                                                                   at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:232)
                                                                                   at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:70)
                                                                                   at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:165)
                                                                                   at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:162)
                                                                                   at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
                                                                                   at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                                                   at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1196)
                                                                                   at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1166)
                                                                                   at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1099)
                                                                                   at com.facebook.react.ReactInstanceManager.access$800(ReactInstanceManager.java:112)
                                                                                   at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:927)
                                                                                   at java.lang.Thread.run(Thread.java:818)
12-24 15:38:19.825 1660-2365/system_process W/ActivityManager:   Force finishing activity com.almaseshomal.baamanbusiness/.MainActivity
12-24 15:38:19.835 1224-1277/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 454656
                                                 
                                                 
                                                 [ 12-24 15:38:19.850  1660: 2365 D/         ]
                                                 HostConnection::get() New Host Connection established 0x7ff6649fc8c0, tid 2365
12-24 15:38:19.930 3417-3438/com.almaseshomal.baamanbusiness E/Surface: getSlotFromBufferLocked: unknown buffer: 0xe1694780
12-24 15:38:19.965 2053-2261/com.android.launcher3 D/EGL_emulation: eglMakeCurrent: 0x7ff672fd3f20: ver 3 0 (tinfo 0x7ff6747c5fa0)
12-24 15:38:19.974 1660-2167/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:19.993 1660-1730/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
12-24 15:38:19.995 1660-1730/system_process D/EGL_emulation: eglCreateContext: 0x7ff672fd0820: maj 3 min 0 rcv 3
12-24 15:38:19.996 1660-1730/system_process D/EGL_emulation: eglMakeCurrent: 0x7ff672fd0820: ver 3 0 (tinfo 0x7ff668fe1ae0)
12-24 15:38:19.997 1660-1730/system_process E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
12-24 15:38:19.997 1660-1730/system_process E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
12-24 15:38:20.010 1660-1730/system_process D/EGL_emulation: eglMakeCurrent: 0x7ff672fd0820: ver 3 0 (tinfo 0x7ff668fe1ae0)
12-24 15:38:20.503 1660-1660/system_process I/ActivityManager: Killing 2623:com.google.android.calendar/u0a22 (adj 15): empty #17
12-24 15:38:20.505 3417-3438/com.almaseshomal.baamanbusiness D/EGL_emulation: eglMakeCurrent: 0xef0d4900: ver 3 0 (tinfo 0xef0d2470)
12-24 15:38:20.508 3417-3438/com.almaseshomal.baamanbusiness E/Surface: getSlotFromBufferLocked: unknown buffer: 0xe1694460
12-24 15:38:20.511 2053-2261/com.android.launcher3 W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
12-24 15:38:20.511 2053-2261/com.android.launcher3 W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
12-24 15:38:24.183 1660-1866/system_process I/ActivityManager: Killing 2805:com.google.android.gms.ui/u0a8 (adj 15): empty #17
12-24 15:38:25.315 2508-2726/com.google.android.gms I/ContentMaintenance: Pruning caches...
12-24 15:38:25.316 2508-2726/com.google.android.gms I/ContentMaintenance: Internal cache bytes used: 0; limit: 100000000; download size: 0
12-24 15:38:25.320 2508-2726/com.google.android.gms I/ContentMaintenance: Cache pruning complete.
12-24 15:38:25.324 2508-2726/com.google.android.gms I/ContentMaintenance: Beginning garbage collection.
12-24 15:38:25.327 2508-2726/com.google.android.gms I/RealtimeCacheCleanup: Beginning Realtime garbage collection.
12-24 15:38:25.327 2508-2726/com.google.android.gms I/RealtimeCacheCleanup: Finished Realtime garbage collection.
12-24 15:38:25.327 2508-2726/com.google.android.gms I/ContentMaintenance: Finished garbage collection.
12-24 15:38:25.441 1660-2167/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:25.449 1660-1745/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:25.450 1660-1672/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:25.457 1660-1671/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:25.503 1660-1672/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:43.331 1224-1291/? D/hwcomposer: hw_composer sent 570 syncs in 60s
12-24 15:38:49.919 1660-1711/system_process W/ActivityManager: Unable to start service Intent { act=com.google.android.gms.drive.ApiService.RESET_AFTER_BOOT flg=0x4 cmp=com.google.android.gms/.drive.api.ApiService (has extras) } U=0: not found
12-24 15:38:49.941 1660-1672/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:49.945 1660-2167/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:49.945 1660-2897/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:49.948 1660-1671/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:49.950 2508-4154/com.google.android.gms W/System: ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86_64
12-24 15:38:49.956 1660-2364/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
12-24 15:38:55.838 2508-3345/com.google.android.gms W/art: No such thread id for suspend: 75
12-24 15:39:10.521 2508-2674/com.google.android.gms I/CastDatabase: Saving the database
12-24 15:39:10.536 2508-2674/com.google.android.gms I/SQLiteCastStore: [CastNetworkInfo] saved: 0, skipped: 0, [CastDeviceInfo]: saved 0, skipped 0, Paired Guest Mode DeviceInfo] saved: 0, skipped: 0.
```

**Comment by hiradary** [comment]
بنظرم ممکنه بخاطر گوگل مپس باشه

**Comment by hiradary** [comment]
:البته این تست روی شبیه ساز
Android 6.0 و API 23
انجام شده

**Comment by Husseinhj** [comment]
<p dir="rtl">اطلاعات گریدل خودتون رو با حفظ مسائل امنیتی برای ما اینجا قرار بدید تا نسخه buildTools , targetSdk  و همینطور نسخه playService </p>
<p dir="rtl">چون شما از کتابخانه ریکت‌نیتو pureJs استفاده می‌کنید چابک کد نیتیوی نداره که این مشکل برای شما پیش بیاد</p>

**Comment by hiradary** [comment]
```
compileSdkVersion   = 26
targetSdkVersion    = 26
buildToolsVersion   = "26.0.2"
supportLibVersion   = "26.0.2"
googlePlayServicesVersion = "11.8.0"
```

احتمال زیاد بخاطر
react-native-push-notification
هستش

**Comment by Husseinhj** [comment]
<p dir="rtl">بنظر این موضوع در <a href="https://github.com/react-native-community/react-native-maps/issues/818">issue #818</a> در ریکت‌نیتو حل شده مطابق آن پیش بروید و نتیجه آن را اطلاع دهید</p>

**Comment by mahshadalishahi** [comment]
منم دقیقا این مشکلو دارم و فکر میکنم مشکل از ریکت نیتیو مپس هستش 
لینکی که گذاشتید کمکی بهم نکرد

**Comment by mahshadalishahi** [comment]
اروری که میگیرم اینه :

``` java
01-13 17:42:31.753 23531-23569/com.izisys.confectionary E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.izisys.confectionary, PID: 23531
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source:0)
        at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:0)
        at com.agontuk.RNFusedLocation.RNFusedLocationModule.<init>(RNFusedLocationModule.java:96)
        at com.agontuk.RNFusedLocation.RNFusedLocationPackage.createNativeModules(RNFusedLocationPackage.java:26)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.izisys.confectionary-6c4omcUhB5CziZR6Dk4BXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.izisys.confectionary-6c4omcUhB5CziZR6Dk4BXQ==/lib/x86, /data/app/com.izisys.confectionary-6c4omcUhB5CziZR6Dk4BXQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source:0) 
        at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:0) 
        at com.agontuk.RNFusedLocation.RNFusedLocationModule.<init>(RNFusedLocationModule.java:96) 
        at com.agontuk.RNFusedLocation.RNFusedLocationPackage.createNativeModules(RNFusedLocationPackage.java:26) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">منم دقیقا این مشکلو دارم و فکر میکنم مشکل از ریکت نیتیو مپس هستش</p>
<p dir="rtl">لینکی که گذاشتید کمکی بهم نکرد</p></blockquote>
<p dir="rtl">@mahshadalishahi 
خطایی که شما ارسال کردید متفاوت هست با پاسخی که مطرح شده بود</p>
<p dir="rtl">لطفا نسخه PlayServices رو بفرمایید</p>
<p dir="rtl">بنظر این مشکل در <a href="https://github.com/react-native-community/react-native-google-signin/issues/417">issue 417</a> ریکت‌نیتو مطرح شده. </p>

**Comment by mahshadalishahi** [comment]
نسخه playservices: 
                            googlePlayServicesVersion = "11.0.0"

**Comment by mahshadalishahi** [comment]
> > منم دقیقا این مشکلو دارم و فکر میکنم مشکل از ریکت نیتیو مپس هستش
> > لینکی که گذاشتید کمکی بهم نکرد
> 
> @mahshadalishahi خطایی که شما ارسال کردید متفاوت هست با پاسخی که مطرح شده بود
> 
> لطفا نسخه PlayServices رو بفرمایید
> 
> بنظر این مشکل در [issue 417](https://github.com/react-native-community/react-native-google-signin/issues/417) ریکت‌نیتو مطرح شده.

نسخه playservices:
googlePlayServicesVersion = "11.0.0"

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">بنظر این مشکل در <a href="https://github.com/react-native-community/react-native-google-signin/issues/417">issue 417</a> ریکت‌نیتو مطرح شده.</p>
</blockquote>
<p dir="rtl">آیا issue مرتبط با مشکل شما که در بالا لینک شده رو مطالعه کردید؟ </p>

**Comment by Husseinhj** [comment]
<p dir="rtl">در کتابخانه <strong>PureJS</strong> چابک هیچ کد Native وجود نداره و این خطاها بخاطر عدم همخوانی پیکیج‌هایی هست که استفاده میشه و چون کتابخانه <code>react-native-push-notification</code> برای پوش باید از <strong dir="rtl">play services</strong> استفاده کنه دقت کنید که کتابخانه‌های دیگه‌ای که از <strong dir="rtl">play serivces</strong> استفاده می‌کنند، نسخه <strong dir="rtl">play services</strong> آنها یکسان باشد. </p>

**Comment by mahshadalishahi** [comment]
> > بنظر این مشکل در [issue 417](https://github.com/react-native-community/react-native-google-signin/issues/417) ریکت‌نیتو مطرح شده.
> 
> آیا issue مرتبط با مشکل شما که در بالا لینک شده رو مطالعه کردید؟

بله مطالعه کردم و کمکم کرد مشکلم حل شد ممنونم
